apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "first-pipeline.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "first-pipeline.labels" . | nindent 4 }}
data:
  PORT: "{{ .Values.config.port }}"
  NODE_ENV: "{{ .Values.config.nodeEnv }}"
