apiVersion: v1
kind: Service
metadata:
  name: first-pipeline
  namespace: first-pipeline
  labels:
    app: first-pipeline
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: first-pipeline
---
apiVersion: v1
kind: Service
metadata:
  name: first-pipeline-nodeport
  namespace: first-pipeline
  labels:
    app: first-pipeline
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
    nodePort: 30000
  selector:
    app: first-pipeline
